preview_backfill:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: appliance_energy_cost
    start:
      required: true
      selector:
        datetime:
    end:
      required: false
      selector:
        datetime:
    appliances:
      required: false
      selector:
        entity:
          multiple: true
          filter:
            domain: sensor
            device_class: energy
    strict:
      required: false
      default: true
      selector:
        boolean:
import_backfill:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: appliance_energy_cost
    start:
      required: true
      selector:
        datetime:
    end:
      required: false
      selector:
        datetime:
    appliances:
      required: false
      selector:
        entity:
          multiple: true
          filter:
            domain: sensor
            device_class: energy
    strict:
      required: false
      default: true
      selector:
        boolean:
    confirm:
      required: false
      default: false
      selector:
        boolean:
    overwrite_existing:
      required: false
      default: false
      selector:
        boolean:
    initial_cost:
      required: false
      selector:
        number:
          mode: box
          step: any
calibrate_cost:
  target:
    entity:
      domain: sensor
      integration: appliance_energy_cost
  fields:
    value:
      required: true
      selector:
        number:
          mode: box
          step: any
